### ISSUE TITLE
Thresholding to binary predictions not working with a number

### ISSUE THREAD

**Issue by hpilat** [EvolEcolGroup/tidysdm#40]
I've been trying to threshold my predictions into binary presence/absence, and I can't seem to input just a number into `class_thresh.` The help file for `calib_class_thresh` shows examples with input `"tss_max"`, `"kap_max"`, and `"sensitivity"`, all of which work (including `"sensitivity"` with a specified target value. However, if I input just a number into `class_thresh`, I get an error message saying:

Error in `dplyr::bind_rows()`:
! Can't combine `..1$optim_value` <double> and `..2$optim_value` <character>.
Run `rlang::last_trace()` to see where the error occurred.

I'm wondering if I'm inputting the numbers incorrectly, or if there's a larger issue at hand. If possible, it would be nice to have an example in the help file of just a number inputted, so we can be sure it's formatted correctly. It sounds straightforward enough, but I haven't been able to make the command work with just a number. Another question I have is the sensitivity character metric the sum of sensitivity and specificity (maxSSS for example)? Or just sensitivity alone? Some clarity on this particular metric would be great. Thanks in advance!

**Comment by dramanica** [comment]
`calib_class_treshold` is designed to calibrate the threshold based on some metric, so it does not take a fixed threshold. The bug is in `predict`, which asks for calibration even when you provide a single value (rather than a metric). I'll fix that in the next couple of days. In the mean time, as a simple work around, just predict without creating a class, and then you can turn the continuous raster into a binary one with:
`new_raster <- old_raster>=0.6`
New raster is now a binary raster with the desired threshold. Does that help?

**Comment by dramanica** [comment]
@hpilat Actually, this was easier to fix than I thought. If you grab the `dev` version, setting `class_thresh` in `predict` to a fixed values should now work. To get the dev version ,use:
`devtools::install_github("EvolEcolGroup/tidysdm", ref = "dev")`
Then, this code works for me:
`pred_class <- predict(test_ens,
                        new_data = two_class_dat, type = "class", class_thresh = 0.4,
                        fun = c("mean", "median")`
